### ISSUE TITLE
Option to display "minutes left" in menu bar

### ISSUE THREAD

**Issue by jothirams** [felixpalmer/Cherrola#4]
Hello,

Currently there is a clock kind of display on the menu bar. Along with that or replacing that, would it be possible to display the number of minutes left and when the last minute has also reached,to change that to display the seconds.

This is more a feature request, than a bug

**Comment by felixpalmer** [comment]
Personally I prefer the "analogue" style as it is easier to read at a glance, and as such cannot see myself adding this feature in the near future. 

If you'd like to change it yourself, the relevant code is in https://github.com/felixpalmer/Cherrola/blob/master/Cherrola/StatusItemView.m#L30

I'm also hesitant to add this option as it would mean having to have somewhere for the user to configure the app, like a settings dialog, which currently doesn't exist.
