### ISSUE TITLE
Option to hide or cancel the break

### ISSUE THREAD

**Issue by jothirams** [felixpalmer/Cherrola#5]
Hello,

I just downloaded and ran the app from Xcode directly. After 25 minutes, for the 5 min break it filled up my screen with the break time. Instead of this behaviour, could it prompt for an option for short or long break after the time ends.

Also, while in break, the break time can be shown in the menu bar with a different color, say green, while the system is still accessible. 

Thanks.

**Comment by felixpalmer** [comment]
Sorry, but the entire point of the app is to force you to take a break whether you like it or not, once the session is up (I've updated the main page to make this clearer).

As for prompting for the length of break, I'm not sure this really adds much, and it makes the workflow more complicated

**Comment by jothirams** [comment]
When you are working individually it makes sense, however, when I'm in the office environment it may not be the best method when I'm working with a collegue or doing a presentation. Anyway, looks like the goal of the app is different in this. It is fine.

**Comment by felixpalmer** [comment]
I completely get that, and have to be careful to disable it when doing a presentation or similar myself. However, for me having a button to skip the break is just too tempting, so I've taken this more aggressive approach.
